// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/solo-io/gloo/projects/gloo/pkg/plugins/kubernetes (interfaces: KubePluginSharedFactory)

// Package mock_kubernetes is a generated GoMock package.
package mock_kubernetes

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	v1 "k8s.io/client-go/listers/discovery/v1"
)

// MockKubePluginSharedFactory is a mock of KubePluginSharedFactory interface.
type MockKubePluginSharedFactory struct {
	ctrl     *gomock.Controller
	recorder *MockKubePluginSharedFactoryMockRecorder
}

// MockKubePluginSharedFactoryMockRecorder is the mock recorder for MockKubePluginSharedFactory.
type MockKubePluginSharedFactoryMockRecorder struct {
	mock *MockKubePluginSharedFactory
}

// NewMockKubePluginSharedFactory creates a new mock instance.
func NewMockKubePluginSharedFactory(ctrl *gomock.Controller) *MockKubePluginSharedFactory {
	mock := &MockKubePluginSharedFactory{ctrl: ctrl}
	mock.recorder = &MockKubePluginSharedFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKubePluginSharedFactory) EXPECT() *MockKubePluginSharedFactoryMockRecorder {
	return m.recorder
}

// EndpointSliceLister mocks base method.
func (m *MockKubePluginSharedFactory) EndpointSliceLister(arg0 string) v1.EndpointSliceLister {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EndpointSliceLister", arg0)
	ret0, _ := ret[0].(v1.EndpointSliceLister)
	return ret0
}

// EndpointSliceLister indicates an expected call of EndpointSliceLister.
func (mr *MockKubePluginSharedFactoryMockRecorder) EndpointSliceLister(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EndpointSliceLister", reflect.TypeOf((*MockKubePluginSharedFactory)(nil).EndpointSliceLister), arg0)
}

// Subscribe mocks base method.
func (m *MockKubePluginSharedFactory) Subscribe() <-chan struct{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe")
	ret0, _ := ret[0].(<-chan struct{})
	return ret0
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockKubePluginSharedFactoryMockRecorder) Subscribe() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockKubePluginSharedFactory)(nil).Subscribe))
}

// Unsubscribe mocks base method.
func (m *MockKubePluginSharedFactory) Unsubscribe(arg0 <-chan struct{}) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Unsubscribe", arg0)
}

// Unsubscribe indicates an expected call of Unsubscribe.
func (mr *MockKubePluginSharedFactoryMockRecorder) Unsubscribe(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unsubscribe", reflect.TypeOf((*MockKubePluginSharedFactory)(nil).Unsubscribe), arg0)
}
